name: catcheye-guard-raspbian
services:
  catcheye-guard-dev:
    extends:
      file: docker-compose.base.yml
      service: robot-base
    image: ghcr.io/itschurry/catcheye-guard:develop-raspbian
    container_name: catcheye-guard-develop-raspbian
    working_dir: $HOME/catcheye-guard
    environment:
      - BUILD_TYPE=develop
    volumes:
      - ../:$HOME/catcheye-guard:rw
      - $HOME/shared:/mnt/shared:rw
      - $HOME/.ssh:/home/user/.ssh:ro
      - $HOME/.ssh/known_hosts:/home/user/.ssh/known_hosts:rw
      - vscode_server:/home/user/.vscode-server:rw
      - vscode_server_ext:/home/user/.vscode-server/extensions:rw
      - vscode_server_data:/home/user/.vscode-server/data:rw

    command: bash
    stdin_open: true
    tty: true

volumes:
  vscode_server:
  vscode_server_ext:
  vscode_server_data:
