services:
  robot-base:
    env_file:
      - .env
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        USERNAME: ${USER:-appuser}
        HOME: ${HOME:-/home/${USER:-appuser}}
